type Provincias {
  provincia: String!
  governador: Governador!
  vice_governadores: [Vice_governadores!]!
  municipios: [Municipios]!
  informacoes_adicionais: InformacoesAdicionais!
}

input InputNomeProvincia {
  provincia: String!
}

type Governador {
  nome: String!
  data_nomeacao: String!
}

type Vice_governadores {
  nome: String!
  cargo: String!
}

type InformacoesAdicionais {
  capital: String
  linguas: [String]
  densidade_populacional: String
  data_fundacao: String
  extensao: String
  etnia: [String]
  numero_municipios: String
}

type Municipios {
  nome: String!
  comunas: [String]
  distritos: [String]
  data_fundacao: String
  administrador: String
}

type Query {
  provincias: [Provincias!]!
  provincia(data: InputNomeProvincia!): Provincias!
}
