import { TProvincias } from "@/@types/provincias";

export const provincias: TProvincias[] = [
  {
    provincia: "Cabinda",
    governador: {
      nome: "Suzana Fernanda Pemba Massiala de Abreu",
      data_nomeacao: "15-07-2024",
    },
    vice_governadores: [
      {
        cargo: "SERVIÇOS ECONÓMICOS",
        nome: "Macário Romão Lembe",
      },
      {
        cargo: "SECTOR POLÍTICO SOCIAL",
        nome: "Miguel dos Santos de Oliveira",
      },
    ],
    municipios: [
      {
        nome: "Belize",
        comunas: ["Luali", "Belize"],
        distritos: [],
        data_fundacao: "",
        administrador: "",
      },
      {
        nome: "Buco-Zau",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "Oscar Dilo",
      },
      {
        nome: "Cabinda",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "Guilherme Pereira",
      },
      {
        nome: "Cacongo",
        comunas: ["Dinge", "Lândana"],
        distritos: [],
        data_fundacao: "",
        administrador: "Armando Camilo do Carmo Mbuiti",
      },
      {
        nome: "Miconje",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "",
      },
      {
        nome: "Massabi",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "",
      },
      {
        nome: "Necuto",
        comunas: ["Necuto", "Inhuca"],
        distritos: [],
        data_fundacao: "",
        administrador: "",
      },
      {
        nome: "Tando Zinze",
        comunas: ["Tando Zinze", "Malembo"],
        distritos: [],
        data_fundacao: "",
        administrador: "",
      },
      {
        nome: "Liambo",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "",
      },
      {
        nome: "Ngoio",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "",
      },
    ],
    informacoes_adicionais: {
      capital: "Cabinda",
      linguas: ["Português", "Fiote", "Kikongo"],
      densidade_populacional: "00",
      data_fundacao: "28-02-1862",
      extensao: "7.283 km²",
      etnia: ["Bakongo"],
      numero_municipios: 10,
    },
  },
  {
    provincia: "Zaire",
    governador: {
      nome: "Adriano Mendes de Carvalho",
      data_nomeacao: "16-09-2022",
    },
    vice_governadores: [
      {
        cargo: "SERVIÇOS TÉCNICOS E INFRA-ESTRUTURAS",
        nome: "Ângela Maria Botelho de Carvalho Diogo",
      },
      {
        cargo: "SECTOR POLÍTICO, SOCIAL E ECONÓMICO",
        nome: "Afonso Nzolamesso",
      },
    ],
    municipios: [
      {
        nome: "Mbanza Kongo",
        comunas: ["Mbanza Kongo", "Caluca", "Madimba", "Quiende"],
        distritos: [],
        data_fundacao: "",
        administrador: "Manuel Nsiansoki Gomes",
      },
      {
        nome: "Soyo",
        comunas: ["Soyo", "Pedra de Feitiço"],
        distritos: [],
        data_fundacao: "2024-03-28",
        administrador: "José Mendes Belo",
      },
      {
        nome: "Nzeto",
        comunas: ["Nzeto", "Musserra", "Quibala Norte"],
        distritos: [],
        data_fundacao: "",
        administrador: "Ketuzaioko Domingos Gomes Pinda",
      },
      {
        nome: "Cuimba",
        comunas: ["Cuimba", "Buela", "Luvaca"],
        distritos: [],
        data_fundacao: "",
        administrador: "Isabel Fineza Almeida Queba Salvador",
      },
      {
        nome: "Nóqui",
        comunas: ["Mpala"],
        distritos: [],
        data_fundacao: "",
        administrador: "Manuel Jose Antonio",
      },
      {
        nome: "Tomboco",
        comunas: ["Tomboco", "Quinsimba", "Quinzau"],
        distritos: [],
        data_fundacao: "",
        administrador: "Alberto António Dos Santos",
      },
      {
        nome: "Luvo",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "",
      },
      {
        nome: "Lufico",
        comunas: ["Lufico"],
        distritos: [],
        data_fundacao: "",
        administrador: "",
      },
      {
        nome: "Quêlo",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "",
      },
      {
        nome: "Serra de Canda",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "",
      },
      {
        nome: "Quindeje",
        comunas: ["Quibala - Norte", "Quindeje"],
        distritos: [],
        data_fundacao: "",
        administrador: "",
      },
    ],
    informacoes_adicionais: {
      capital: "Mbanza Kongo",
      linguas: ["Português", "Kikongo"],
      densidade_populacional: "00",
      data_fundacao: "01-04-1961",
      extensao: "40.130 km²",
      etnia: ["Bakongo"],
      numero_municipios: 11,
    },
  },
  {
    provincia: "Uíge",
    governador: {
      nome: "José Carvalho da Rocha",
      data_nomeacao: "16-09-2022",
    },
    vice_governadores: [
      {
        cargo: "SECTOR POLÍTICO, SOCIAL E ECONÓMICO",
        nome: "Sónia Arlete Fernandes Domingos",
      },
      {
        cargo: "SERVIÇOS TÉCNICOS E INFRA-ESTRUTURAS",
        nome: "Helena da Cruz Vieira Dias Pereira",
      },
    ],
    municipios: [
      {
        nome: "Uíge",
        comunas: ["Uíge", "Luanga", "Casseche", "Cancungo"],
        distritos: [],
        data_fundacao: "",
        administrador: "José Raimundo Almeida Teca",
      },
      {
        nome: "Cangola",
        comunas: ["Cangola", "Bengo", "Caiongo"],
        distritos: [],
        data_fundacao: "",
        administrador: "Kiaku Fernandes Jorge",
      },
      {
        nome: "Ambuíla",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "Justino Lourenço Kuiassana",
      },
      {
        nome: "Bembe",
        comunas: ["Bembe", "Mabaia"],
        distritos: [],
        data_fundacao: "",
        administrador: "Gildo Laurindo Unigénito",
      },
      {
        nome: "Nova Esperança",
        comunas: ["Nova Esperança", "Buenga - Sul", "Cuilo Camboso"],
        distritos: [],
        data_fundacao: "",
        administrador: "Faustino Nguange Simão",
      },
      {
        nome: "Bungo",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "Salambiacu Manuel Kubanza",
      },
      {
        nome: "Milunga",
        comunas: ["Milunga", "Macocola"],
        distritos: [],
        data_fundacao: "",
        administrador: "Euclides Jorge Laurindo Garcia",
      },
      {
        nome: "Damba",
        comunas: ["Damba", "Petecusso", "Camatambo", "Lêmboa"],
        distritos: [],
        data_fundacao: "1911-05-06",
        administrador: "Eulária Julieta Chiangango Martins Dombaxe",
      },
      {
        nome: "Maquela do Zombo",
        comunas: ["Maquela do Zombo", "Quibocolo"],
        distritos: [],
        data_fundacao: "",
        administrador: "Samalando Sebastião Muginga",
      },
      {
        nome: "Mucaba",
        comunas: ["Mucaba", "Uando Mucaba"],
        distritos: [],
        data_fundacao: "",
        administrador: "Carlos Alberto David",
      },
      {
        nome: "Negage",
        comunas: ["Negage", "Dimuca", "Quisseque"],
        distritos: [],
        data_fundacao: "",
        administrador: "Delfina António Henriques",
      },
      {
        nome: "Puri",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "Silvina António Figueiredo",
      },
      {
        nome: "Quimbele",
        comunas: ["Quimbele", "Icoca"],
        distritos: [],
        data_fundacao: "",
        administrador: "Afonso Manuel",
      },
      {
        nome: "Dange Quitexe",
        comunas: ["Quitexe", "Aldeia Viçosa"],
        distritos: [],
        data_fundacao: "",
        administrador: "Dionísia Fernandes António",
      },
      {
        nome: "Sanza Pombo",
        comunas: ["Sanza Pombo", "Cuilo Pombo", "Uamba", "Alfândega"],
        distritos: [],
        data_fundacao: "",
        administrador: "Santos Coxe Catúdico",
      },
      {
        nome: "Songo",
        comunas: ["Songo", "Quivuenga"],
        distritos: [],
        data_fundacao: "",
        administrador: "Maurício Luís Pascoal",
      },
      {
        nome: "Sacandica",
        comunas: ["Sacandica", "Cuilo Futa", "Béu"],
        distritos: [],
        data_fundacao: "",
        administrador: "Manzambi Chico João",
      },
      {
        nome: "Nsosso",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "Maria de Lourdes Fernando",
      },
      {
        nome: "Lucunga",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "Manuel Fernando Dafula Dias",
      },
      {
        nome: "Quipedro",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "Suzana António Prata",
      },
      {
        nome: "Massau",
        comunas: ["Massau", "Macolo"],
        distritos: [],
        data_fundacao: "",
        administrador: "Ndolu Mucala",
      },
      {
        nome: "Vista Alegre",
        comunas: ["Vista Alegre", "Cambamba"],
        distritos: [],
        data_fundacao: "",
        administrador: "Ângela Augusto Cruz",
      },
      {
        nome: "Alto Zaza",
        comunas: ["Alto Zaza", "Cuango Calumbo"],
        distritos: [],
        data_fundacao: "",
        administrador: "Fátima Igraça José",
      },
    ],
    informacoes_adicionais: {
      capital: "Uíge",
      linguas: ["Português", "Kikongo", "Kimbundu"],
      densidade_populacional: "00",
      data_fundacao: "31-05-1887",
      extensao: "58.698 km²",
      etnia: ["Bakongo", "Ambundu"],
      numero_municipios: 23,
    },
  },
  {
    provincia: "Bengo",
    governador: {
      nome: "Maria Antónia Nelumba",
      data_nomeacao: "16-09-2022",
    },
    vice_governadores: [
      {
        cargo: "SECTOR POLÍTICO, SOCIAL E ECONÓMICO",
        nome: "José Francisco Bartolomeu Pedro",
      },
      {
        cargo: "SERVIÇOS TÉCNICOS E INFRA-ESTRUTURAS",
        nome: "Edson Vaz Câmara da Cruz",
      },
    ],
    municipios: [
      {
        nome: "Bula Atumba",
        comunas: ["Bula Atumba", "Quiage"],
        distritos: [],
        data_fundacao: "",
        administrador: "Joaquim Carlos Cangulo Domingos",
      },
      {
        nome: "Dande",
        comunas: ["Caxito", "Mabubas", "Quicabo"],
        distritos: [],
        data_fundacao: "1987-07-24",
        administrador: "Domingos João Lourenço",
      },
      {
        nome: "Quibaxe",
        comunas: ["Coxe", "Paredes", "Quibaxe"],
        distritos: [],
        data_fundacao: "",
        administrador: "Fátima Jesus Pontes Ramos Sebastião",
      },
      {
        nome: "Nambuangongo",
        comunas: ["Canacassala", "Gombe", "Zala"],
        distritos: [],
        data_fundacao: "",
        administrador: "Deolinda Manuel João",
      },
      {
        nome: "Pango Aluquém",
        comunas: ["Pango Aluquém", "Cazuangongo"],
        distritos: [],
        data_fundacao: "",
        administrador: "Rosa Alberto Alfredo",
      },
      {
        nome: "Ambriz",
        comunas: ["Ambriz", "Bela Vista", "Tabi"],
        distritos: [],
        data_fundacao: "1855-06-06",
        administrador: "António Francisco Tingão Mateus",
      },
      {
        nome: "Muxaluando",
        comunas: ["Muxaluando", "Quixico", "Cage Mazumbo"],
        distritos: [],
        data_fundacao: "",
        administrador: "José Domingos Muginga da Silva",
      },
      {
        nome: "Piri",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "Ginga Afonso Miguel dos Santos",
      },
      {
        nome: "Quicunzo",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "Cândido Manuel João",
      },
      {
        nome: "Úcua",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "Lúcia Pedro Mulanvo",
      },
      {
        nome: "Panguila",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "Jorgina Pereira Domingos",
      },
      {
        nome: "Barra do Dande",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "João Giordano da Silva Cristóvão",
      },
    ],
    informacoes_adicionais: {
      capital: "Dande",
      linguas: ["Português", "Kimbundu", "Kikongo"],
      densidade_populacional: "00",
      data_fundacao: "26-04-1980",
      extensao: "31.371 km²",
      etnia: ["Ambundos", "Bakongos"],
      numero_municipios: 12,
    },
  },
  {
    provincia: "Luanda",
    governador: {
      nome: "Luís Manuel da Fonseca Nunes",
      data_nomeacao: "31-10-2024",
    },
    vice_governadores: [
      {
        cargo: "SECTOR POLÍTICO E SOCIAL",
        nome: "Manuel António Gonçalves",
      },
      {
        cargo: "SECTOR ECONÓMICO",
        nome: "Jorge Miguêns Augusto",
      },
    ],
    municipios: [
      {
        nome: "Belas",
        comunas: ["Benfica", "Cabolombo", "Barra do Cuanza", "Ramiros"],
        distritos: [],
        data_fundacao: "",
        administrador: "Arlindo Francisco Vieira dos Santos",
      },
      {
        nome: "Cacuaco",
        comunas: ["Cacuaco", "Kikolo"],
        distritos: [],
        data_fundacao: "",
        administrador: "Fernando Francisco João",
      },
      {
        nome: "Cazenga",
        comunas: ["Cazenga", "Kima Kieza"],
        distritos: [],
        data_fundacao: "",
        administrador: "Nadia Evelise Martins de Sousa Neto",
      },
      {
        nome: "Kilamba Kiaxi",
        comunas: ["Golfe", "Nova Vida"],
        distritos: [],
        data_fundacao: "",
        administrador: "Naulila Masisa Fernandes André",
      },
      {
        nome: "Viana",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "Demétrio António Brás de Sepúlveda",
      },
      {
        nome: "Mussulo",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "Baudílio dos Santos Baptista Vaz",
      },
      {
        nome: "Sambizanga",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "Betânia Elias de Almeida Lopes",
      },
      {
        nome: "Rangel",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "Lourenço Luís Domingos",
      },
      {
        nome: "Maianga",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "Pedro Orlando Afonso Paca",
      },
      {
        nome: "Samba",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "Loide Andreza Féliz António Plácido de Faria",
      },
      {
        nome: "Camama",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "Claudinete Victória Damião Fragoso",
      },
      {
        nome: "Mulenvos",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "Euclides Joaquim Faria da Costa",
      },
      {
        nome: "Kilamba",
        comunas: ["Kilamba", "Vila Flôr"],
        distritos: [],
        data_fundacao: "",
        administrador: "Arlindo Francisco Vieira dos Santos",
      },
      {
        nome: "Hoji Ya Henda",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "José de Oliveira dos Santos Bastos",
      },
      {
        nome: "Ingombota",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "Milca Cuessue Caquesse",
      },
      {
        nome: "Talatona",
        comunas: [],
        distritos: [],
        data_fundacao: "",
        administrador: "Sandra Caetano Batalha",
      },
    ],
    informacoes_adicionais: {
      capital: "Ingombota",
      linguas: ["Português", "Kimbundu"],
      densidade_populacional: "00",
      data_fundacao: "25-01-1576",
      extensao: "18.826 km²",
      etnia: ["Ambundu"],
      numero_municipios: 16,
    },
  },
  {
    provincia: "Cuanza-Norte",
    governador: {
      nome: "João Diogo Gaspar",
      data_nomeacao: "2024-01-17",
    },
    vice_governadores: [
      {
        cargo: "Vice-Governador para os Serviços Técnicos e Infra-Estruturas",
        nome: "Michel Raimundo Luzolo",
      },
      {
        cargo: "Vice-Governadora para o Sector Político, Social e Econômico",
        nome: "Constantina Pereira Furtado Machado",
      },
    ],
    municipios: [
      {
        nome: "Ambaca",
        comunas: ["Camabatela", "Máua", "Bindo"],
        distritos: [],
        administrador: "Domingos Cabuco João Dala",
        data_fundacao: "",
      },
      {
        nome: "Banga",
        comunas: ["Banga", "Cariamba"],
        distritos: [],
        administrador: "Victorino Abel Manuel",
        data_fundacao: "",
      },
      {
        nome: "Bolongongo",
        comunas: [],
        distritos: [],
        administrador: "Gaspar da Silva",
        data_fundacao: "",
      },
      {
        nome: "Cambambe",
        comunas: ["Dondo", "Dange ya Menha", "São Pedro da Quilemba"],
        distritos: [],
        administrador: "Maria Mafuta Difuma Bafutidy",
        data_fundacao: "",
      },
      {
        nome: "Cazengo",
        comunas: ["Caculo Camuiza", "Ndalatando"],
        distritos: [],
        administrador: "Adilson do Amaral",
        data_fundacao: "",
      },
      {
        nome: "Golungo Alto",
        comunas: ["Golungo Alto", "Cambondo", "Quilombo quía Puto"],
        distritos: [],
        administrador: "-",
        data_fundacao: "",
      },
      {
        nome: "Lucala",
        comunas: ["Lucala", "Quiangombe"],
        distritos: [],
        administrador: "Epifânio Sérgio Manuel da Costa Miranda",
        data_fundacao: "",
      },
      {
        nome: "Ngonguembo",
        comunas: ["Quilombo dos Dembos", "Camame", "Cavunga"],
        distritos: [],
        administrador: "Constantino Figueiredo dos Santos",
        data_fundacao: "",
      },
    ],
    informacoes_adicionais: {
      capital: "Cazengo",
      linguas: ["Português", "Kimbundu"],
      densidade_populacional: "0",
      data_fundacao: "1914-08-15",
      extensao: "24.110 km²",
      etnia: ["Ambundu"],
      numero_municipios: 17,
    },
  },
  {
    provincia: "Malanje",
    governador: {
      nome: "Marcos Alexandre Nhunga",
      data_nomeacao: "2022-09-16",
    },
    vice_governadores: [
      {
        cargo: "Vice-Governador para o Sector Político, Social e Econômico",
        nome: "Franco Cazembe Mufinda",
      },
      {
        cargo: "Vice-Governador para os Serviços Técnicos e Infra-Estruturas",
        nome: "Duarte André Ginga",
      },
    ],
    municipios: [
      {
        nome: "Cacuso",
        comunas: ["Cacuso", "Soqueco"],
        distritos: [],
        administrador: "Mateus Baptista Vunge",
        data_fundacao: "",
      },
      {
        nome: "Cahombo",
        comunas: ["Micanda", "Cahombo"],
        distritos: [],
        administrador: "João Isarael Cabamba",
        data_fundacao: "1968-03-31",
      },
      {
        nome: "Calandula",
        comunas: ["Calandula", "Cota"],
        distritos: [],
        administrador: "Kita Ferreira",
        data_fundacao: "",
      },
      {
        nome: "Cambundi Catembo",
        comunas: ["Cambundi Catembo", "Dumba Cambango"],
        distritos: [],
        administrador: "Fernandes Simão Cristóvão João",
        data_fundacao: "",
      },
      {
        nome: "Cangandala",
        comunas: ["Cangandala", "Caribo", "Culamagia"],
        distritos: [],
        administrador: "Dilangue Baião Domingos",
        data_fundacao: "",
      },
      {
        nome: "Kiwaba Nzoji",
        comunas: ["Kiwaba Nzoji", "Mufuma"],
        distritos: [],
        administrador: "José Neves João António",
        data_fundacao: "",
      },
      {
        nome: "Kunda dya Baze",
        comunas: ["Kunda dya Baze", "Lemba"],
        distritos: [],
        administrador: "Maria Elizete Gaspar Afonso da Silva",
        data_fundacao: "",
      },
    ],
    informacoes_adicionais: {
      capital: "Malanje",
      linguas: ["Português", "Kimbundu"],
      densidade_populacional: "0",
      data_fundacao: "1868-02-13",
      extensao: "2.422 km²",
      etnia: ["Ambundu"],
      numero_municipios: 27,
    },
  },
  {
    provincia: "Lunda-Norte",
    governador: {
      nome: "Filomena Elizabete Chitula Miza Aires",
      data_nomeacao: "2024-07-15",
    },
    vice_governadores: [
      {
        cargo: "Vice-Governador para o Sector Político, Social e Econômico",
        nome: "Frederico Inungo Barroso",
      },
      {
        cargo: "Vice-Governador para os Serviços Técnicos e Infra-Estruturas",
        nome: "Domingos Dala",
      },
    ],
    municipios: [
      {
        nome: "Cambulo",
        comunas: ["Cachimo", "Nzage"],
        distritos: [],
        administrador: "Bernardete Cola Cachoco Muacariata",
        data_fundacao: "2024-04-11",
      },
      {
        nome: "Capenda Camulemba",
        comunas: ["Capenda Camulemba", "Xinge"],
        distritos: [],
        administrador: "Maria Teresa Ngambo",
        data_fundacao: "",
      },
      {
        nome: "Caungula",
        comunas: [],
        distritos: [],
        administrador: "Amélia Paula Valente",
        data_fundacao: "",
      },
      {
        nome: "Chitato",
        comunas: [],
        distritos: [],
        administrador: "Cláudio Alves Leni Muteba",
        data_fundacao: "",
      },
      {
        nome: "Cuango",
        comunas: [],
        distritos: [],
        administrador: "Daniel Mutaza",
        data_fundacao: "",
      },
      {
        nome: "Cuílo",
        comunas: ["Caluango", "Cuílo"],
        distritos: [],
        administrador: "Jacinto Valente",
        data_fundacao: "",
      },
    ],
    informacoes_adicionais: {
      capital: "Dundo",
      linguas: ["Português", "Cokwe"],
      densidade_populacional: "0",
      data_fundacao: "1978-07-04",
      extensao: "103.760 km²",
      etnia: ["Cokwe"],
      numero_municipios: 19,
    },
  },
  {
    provincia: "Lunda-Sul",
    governador: {
      nome: "Daniel Félix Neto",
      data_nomeacao: "2022-09-16",
    },
    vice_governadores: [
      {
        cargo: "Vice-Governador para o Sector Político, Social e Econômico",
        nome: "Mendes Lourenço Gaspar",
      },
      {
        cargo: "Vice-Governador para os Serviços Técnicos e Infra-Estruturas",
        nome: "Esmeraldino Cláudio Pemessa Abreu",
      },
    ],
    municipios: [
      {
        nome: "Cacolo",
        comunas: [],
        distritos: [],
        administrador: "Luís Domingos",
        data_fundacao: "",
      },
      {
        nome: "Dala",
        comunas: [],
        distritos: [],
        administrador: "Lote Zeca Moutinho",
        data_fundacao: "",
      },
      {
        nome: "Muconda",
        comunas: [],
        distritos: [],
        administrador: "Isaías Filipe Sacajima",
        data_fundacao: "",
      },
      {
        nome: "Saurimo",
        comunas: ["Mona Quimbundo", "Saurimo"],
        distritos: [],
        administrador: "Adérito Manuel Cahanga Lucano",
        data_fundacao: "",
      },
    ],
    informacoes_adicionais: {
      capital: "Nenhuma capital definida",
      linguas: ["Português", "Cokwe"],
      densidade_populacional: "0",
      data_fundacao: "1895-07-13",
      extensao: "77.636 km²",
      etnia: ["Cokwe"],
      numero_municipios: 14,
    },
  },
  {
    provincia: "Moxico",
    governador: {
      nome: "Ernesto Muangala",
      data_nomeacao: "2022-09-16",
    },
    vice_governadores: [
      {
        cargo: "Vice-Governador para os Serviços Técnicos e Infra-Estruturas",
        nome: "Wilson Agnelo Chinhama Augusto",
      },
    ],
    municipios: [
      {
        nome: "Chiúme",
        comunas: [],
        distritos: [],
        administrador: "Elísio Nazaré Keshipoco",
        data_fundacao: "",
      },
      {
        nome: "Lumbala Nguimbo",
        comunas: ["Lumbala Nguimbo", "Mussuma Mitete", "Sessa"],
        distritos: [],
        administrador: "Benilson Mbambi",
        data_fundacao: "",
      },
      {
        nome: "Camanongue",
        comunas: [],
        distritos: [],
        administrador: "-",
        data_fundacao: "",
      },
      {
        nome: "Léua",
        comunas: ["Léua", "Liangongo"],
        distritos: [],
        administrador: "António Segunda Muquissi",
        data_fundacao: "",
      },
      {
        nome: "Alto Cuito",
        comunas: [],
        distritos: [],
        administrador: "Dikson Macai",
        data_fundacao: "",
      },
      {
        nome: "Lutembo",
        comunas: ["Lutembo", "Luvuei"],
        distritos: [],
        administrador: "Ana Paula Muhanda Da Maia",
        data_fundacao: "",
      },
      {
        nome: "Cangumbe",
        comunas: [],
        distritos: [],
        administrador: "Arminda António",
        data_fundacao: "",
      },
      {
        nome: "Luena",
        comunas: ["Luena", "Cassongo"],
        distritos: [],
        administrador: "Bernardo Muhongo Txissola",
        data_fundacao: "",
      },
      {
        nome: "Cangamba",
        comunas: ["Cangombe", "Cassamba", "Cangamba", "Muié"],
        distritos: [],
        administrador: "Quintas Miúdo Sempieca",
        data_fundacao: "",
      },
      {
        nome: "Lucusse",
        comunas: [],
        distritos: [],
        administrador: "Alzira Cutemba Ramiro",
        data_fundacao: "",
      },
      {
        nome: "Ninda",
        comunas: [],
        distritos: [],
        administrador: "Fidel Guimarães Pinto Luís",
        data_fundacao: "",
      },
      {
        nome: "Lutuai",
        comunas: [],
        distritos: [],
        administrador: "Anastacia Teresa Alfredo Manuel Chicuambi",
        data_fundacao: "",
      },
    ],
    informacoes_adicionais: {
      capital: "Luena",
      linguas: ["Português", "Cokwe", "Nganguela"],
      densidade_populacional: "0",
      data_fundacao: "1917-09-15",
      extensao: "223.023 km²",
      etnia: ["Ovanga"],
      numero_municipios: 12,
    },
  },
  {
    provincia: "Cuando Cubango",
    governador: {
      nome: "José Martins",
      data_nomeacao: "2022-09-19",
    },
    vice_governadores: [
      {
        cargo: "Vice-Governadora para o Sector Político, Social e Econômico",
        nome: "Helena Lourenço Chimena",
      },
      {
        cargo: "Vice-Governador para os Serviços Técnicos e Infra-Estruturas",
        nome: "João Bonifácio Cassanga",
      },
    ],
    municipios: [
      {
        nome: "Calai",
        comunas: [],
        distritos: [],
        administrador: "Adélia Muambeno Samuel",
        data_fundacao: "",
      },
      {
        nome: "Cuangar",
        comunas: [],
        distritos: [],
        administrador: "Benjamim Dumba João",
        data_fundacao: "",
      },
      {
        nome: "Cuchi",
        comunas: [],
        distritos: [],
        administrador: "Severino Sawanda Tchimbolo",
        data_fundacao: "",
      },
      {
        nome: "Cutato",
        comunas: ["Cutato", "Vissati"],
        distritos: [],
        administrador: "Luís Paulo Vissunjo",
        data_fundacao: "",
      },
      {
        nome: "Caiundo",
        comunas: ["Caiundo", "Jamba Cueio"],
        distritos: [],
        administrador: "Manuel Moura Jamba",
        data_fundacao: "",
      },
      {
        nome: "Longa",
        comunas: ["Longa", "Baixo Longa"],
        distritos: [],
        administrador: "José Ernesto da Silva",
        data_fundacao: "",
      },
      {
        nome: "Menongue",
        comunas: [],
        distritos: [],
        administrador: "Roberto de Jesus Kalie Biwango",
        data_fundacao: "",
      },
      {
        nome: "Nancova",
        comunas: ["Nancova", "Rito"],
        distritos: [],
        administrador: "Augusto Domingos Manuel",
        data_fundacao: "",
      },
      {
        nome: "Savate",
        comunas: ["Savate", "Bondo Caíla"],
        distritos: [],
        administrador: "Ana Paula Baptista",
        data_fundacao: "",
      },
      {
        nome: "Chinguanja",
        comunas: [],
        distritos: [],
        administrador: "Manuel Tuta Mateus Miguel",
        data_fundacao: "",
      },
      {
        nome: "Mavengue",
        comunas: ["Mavengue", "Maué"],
        distritos: [],
        administrador: "Laura Caveto",
        data_fundacao: "",
      },
    ],
    informacoes_adicionais: {
      capital: "Menongue",
      linguas: ["Português", "Nganguela"],
      densidade_populacional: "0",
      data_fundacao: "1961-10-21",
      extensao: "199.049 km²",
      etnia: ["Ovanganguela"],
      numero_municipios: 11,
    },
  },
  {
    provincia: "Cunene",
    governador: {
      nome: "Gerdina Ulipamue Didalewa",
      data_nomeacao: "2022-09-16",
    },
    vice_governadores: [
      {
        cargo: "Vice-Governador para o Sector Político, Social e Econômico",
        nome: "Apolo Ndinoulenga",
      },
      {
        cargo: "Vice-Governador para os Serviços Técnicos e Infra-Estruturas",
        nome: "António Gilberto Augusto Matias",
      },
    ],
    municipios: [
      {
        nome: "Cahama",
        comunas: ["Cahama", "Otchinjau"],
        distritos: [],
        administrador: "Orlando Alberto Kamati",
        data_fundacao: "",
      },
      {
        nome: "Cuanhama",
        comunas: ["Ondjiva", "Môngua"],
        distritos: [],
        administrador: "José Felisberto Kalomo",
        data_fundacao: "",
      },
      {
        nome: "Curoca",
        comunas: [],
        distritos: [],
        administrador: "Manuel Domingos Taby",
        data_fundacao: "",
      },
      {
        nome: "Cuvelai",
        comunas: [],
        distritos: [],
        administrador: "Germano Baptista Nambalo",
        data_fundacao: "",
      },
      {
        nome: "Namacunde",
        comunas: [],
        distritos: [],
        administrador: "Cristiana Nameomunu",
        data_fundacao: "",
      },
      {
        nome: "Ombandja",
        comunas: ["Xangongo", "Ombala yo Mungu"],
        distritos: [],
        administrador: "Elizett Gloriosa Nené da Esperança Ndahangehodi Kondjasili Mwamelungi",
        data_fundacao: "",
      },
      {
        nome: "Mupa",
        comunas: [],
        distritos: [],
        administrador: "Graça Quaresma Nené Ndenelao Chityeni",
        data_fundacao: "",
      },
      {
        nome: "Chissuata",
        comunas: [],
        distritos: [],
        administrador: "Eufrásia Kantiqui Wakussanga",
        data_fundacao: "",
      },
    ],
    informacoes_adicionais: {
      capital: "Cuanhama",
      linguas: ["Português", "Oshiwambo"],
      densidade_populacional: "0",
      data_fundacao: "1970-07-10",
      extensao: "78.342 km²",
      etnia: ["Ovambu"],
      numero_municipios: 14,
    },
  },
  {
    provincia: "Namibe",
    governador: {
      nome: "Augusto Archer de Sousa Mangueira",
      data_nomeacao: "2022-02-16",
    },
    vice_governadores: [
      {
        cargo: "Vice-Governadora para os Serviços Técnicos e Infra-Estruturas",
        nome: "Ema Samali Henriques da Silva",
      },
      {
        cargo: "Vice-Governador para o Sector Político, Social e Econômico",
        nome: "Abel do Rosário Kapitango",
      },
    ],
    municipios: [
      {
        nome: "Moçâmedes",
        comunas: [],
        distritos: [],
        administrador: "Abelardo Lemba",
        data_fundacao: "",
      },
      {
        nome: "Camucuio",
        comunas: ["Camucuio", "Mamué", "Chingo"],
        distritos: [],
        administrador: "Manuel Canivete",
        data_fundacao: "",
      },
      {
        nome: "Bibala",
        comunas: ["Bibala", "Capangombe", "Caitou", "Lola"],
        distritos: [],
        administrador: "Luzia Tyikele do Carmo Arcanjo",
        data_fundacao: "",
      },
      {
        nome: "Virei",
        comunas: ["Virei", "Cainde"],
        distritos: [],
        administrador: "André Tchimuco Cassinda",
        data_fundacao: "",
      },
      {
        nome: "Tômbua",
        comunas: [],
        distritos: [],
        administrador: "Adilson Amado Marmane Hach",
        data_fundacao: "",
      },
      {
        nome: "Lucira",
        comunas: ["Lucira", "Bentiaba"],
        distritos: [],
        administrador: "Marília João",
        data_fundacao: "",
      },
      {
        nome: "Iona",
        comunas: [],
        distritos: [],
        administrador: "Aristidis Tumbo",
        data_fundacao: "",
      },
      {
        nome: "Sacomar",
        comunas: [],
        distritos: [],
        administrador: "Conceição Elizete Catraio Luís",
        data_fundacao: "",
      },
      {
        nome: "Cacimbas",
        comunas: [],
        distritos: [],
        administrador: "Júlia Morais",
        data_fundacao: "",
      },
    ],
    informacoes_adicionais: {
      capital: "Nenhuma capital definida",
      linguas: ["Português", "Oluherero"],
      densidade_populacional: "0",
      data_fundacao: "1645-07-10",
      extensao: "8.916 km²",
      etnia: ["Minoria Oluyaneka"],
      numero_municipios: 9,
    },
  },
  {
    provincia: "Huíla",
    governador: {
      nome: "Nuno Bernabé Mahapi Dala",
      data_nomeacao: "2022-09-16",
    },
    vice_governadores: [
      {
        cargo: "Vice-Governadora para o Sector Político, Social e Econômico",
        nome: "Maria João Francisco Chipalavela",
      },
      {
        cargo: "Vice-Governador para os Serviços Técnicos e Infra-Estruturas",
        nome: "Hélio Delize Neto de Almeida",
      },
    ],
    municipios: [
      {
        nome: "Caconda",
        comunas: ["Caconda", "Gungue", "Uaba", "Cusse"],
        distritos: [],
        administrador: "Joaquim Sapalo Castilho Cacumba",
        data_fundacao: "",
      },
      {
        nome: "Cacula",
        comunas: ["Cacula", "Tchicuaqueia"],
        distritos: [],
        administrador: "José Mariano Santos",
        data_fundacao: "",
      },
      {
        nome: "Caluquembe",
        comunas: ["Caluquembe", "Calepi", "Negola"],
        distritos: [],
        administrador: "Mariana Chiloca Soma",
        data_fundacao: "",
      },
      {
        nome: "Chibia",
        comunas: ["Chibia", "Jau"],
        distritos: [],
        administrador: "Mateus Mango João Aspirante Baptista",
        data_fundacao: "",
      },
      {
        nome: "Chicomba",
        comunas: ["Chicomba", "Cutenda"],
        distritos: [],
        administrador: "Abel Wandy André",
        data_fundacao: "",
      },
      {
        nome: "Chipindo",
        comunas: ["Chipindo", "Bambi"],
        distritos: [],
        administrador: "Ângelo Singue",
        data_fundacao: "",
      },
      {
        nome: "Lubango",
        comunas: ["Lubango", "Huíla"],
        distritos: [],
        administrador: "Lisender Agnelo Madureira André",
        data_fundacao: "",
      },
      {
        nome: "Quilengues",
        comunas: ["Quilengues", "Impulo", "Dinde"],
        distritos: [],
        administrador: "Adriano Alberto Pedro",
        data_fundacao: "",
      },
    ],
    informacoes_adicionais: {
      capital: "Lubango",
      linguas: ["Português", "Olunhaneka", "Umbundu"],
      densidade_populacional: "0",
      data_fundacao: "1901-09-02",
      extensao: "79.022 km²",
      etnia: ["Ovambu"],
      numero_municipios: 23,
    },
  },
  {
    provincia: "Benguela",
    governador: {
      nome: "Manuel Nunes Júnior",
      data_nomeacao: "2024-10-31",
    },
    vice_governadores: [
      {
        cargo: "Vice-Governador para os Serviços Técnicos e Infra-Estruturas",
        nome: "Adilson Dellany Martins Gonçalves",
      },
      {
        cargo: "Vice-Governadora para o Sector Político, Social e Econômico",
        nome: "Cátia Francisca Gertrudes Tchimbinga Cachuco",
      },
    ],
    municipios: [
      {
        nome: "Baía Farta",
        comunas: [],
        distritos: [],
        administrador: "Evaristo Calopa Mário",
        data_fundacao: "",
      },
      {
        nome: "Balombo",
        comunas: ["Balombo", "Maca Mombolo"],
        distritos: [],
        administrador: "José Cambiete",
        data_fundacao: "",
      },
      {
        nome: "Bocoio",
        comunas: ["Bocoio", "Cubal do Lumbo", "Monte Belo"],
        distritos: [],
        administrador: "João Samuel Herculano Neto",
        data_fundacao: "",
      },
      {
        nome: "Caimbambo",
        comunas: ["Caimbambo", "Caiave", "Viangombe"],
        distritos: [],
        administrador: "Miraldina Marlene Torres Morgado",
        data_fundacao: "",
      },
      {
        nome: "Catumbela",
        comunas: [],
        distritos: [],
        administrador: "Kátia Maria Afonso Teixeira",
        data_fundacao: "",
      },
      {
        nome: "Chongorói",
        comunas: ["Chongorói", "Camuine"],
        distritos: [],
        administrador: "Ernesto Pinto",
        data_fundacao: "",
      },
      {
        nome: "Cubal",
        comunas: [],
        distritos: [],
        administrador: "Paulino Mbinguela Banja",
        data_fundacao: "",
      },
      {
        nome: "Ganda",
        comunas: [],
        distritos: [],
        administrador: "Francisco Salomão Rodrigues Prata",
        data_fundacao: "",
      },
      {
        nome: "Lobito",
        comunas: [],
        distritos: [],
        administrador: "Evaristo Calopa Mário",
        data_fundacao: "",
      },
      {
        nome: "Benguela",
        comunas: [],
        distritos: [],
        administrador: "Paula Marisa Caldeira Lopes Correia",
        data_fundacao: "",
      },
    ],
    informacoes_adicionais: {
      capital: "Nenhuma capital definida",
      linguas: ["Português", "Umbundu", "Ohvanyaneka"],
      densidade_populacional: "0",
      data_fundacao: "1617-05-17",
      extensao: "39.827 km²",
      etnia: ["Ovimbundu", " Ohvanyaneka"],
      numero_municipios: 23,
    },
  },
  {
    provincia: "Huambo",
    governador: {
      nome: "Pereira Alfredo",
      data_nomeacao: "2024-07-15",
    },
    vice_governadores: [
      {
        cargo: "Vice-Governador para o Sector Político, Social e Econômico",
        nome: "Angelino Edmundo Elavoco",
      },
      {
        cargo: "Vice-Governador para os Serviços Técnicos e Infra-Estruturas",
        nome: "Edgar Marcelino dos Santos Hilário",
      },
    ],
    municipios: [
      {
        nome: "Bailundo",
        comunas: ["Bailundo", "Lunge", "Luvemba"],
        distritos: [],
        administrador: "Celestino Piedade Chiqueea",
        data_fundacao: "",
      },
      {
        nome: "Caála",
        comunas: [],
        distritos: [],
        administrador: "Ruben Isaías Chivuta Etome",
        data_fundacao: "",
      },
      {
        nome: "Cachiungo",
        comunas: ["Chinhama", "Cachiungo"],
        distritos: [],
        administrador: "Paulo Moma Kondomboke",
        data_fundacao: "",
      },
      {
        nome: "Chicala Choloanga",
        comunas: ["Mbave", "Chicala"],
        distritos: [],
        administrador: "Adérito Chimuco Samucango",
        data_fundacao: "",
      },
      {
        nome: "Chinjenje",
        comunas: ["Chinjenje", "Chiaca"],
        distritos: [],
        administrador: "Pedro Isaac",
        data_fundacao: "",
      },
      {
        nome: "Ecunha",
        comunas: ["Ecunha", "Quipeio"],
        distritos: [],
        administrador: "Guilhermina Carlos Bacia de Lourdes",
        data_fundacao: "",
      },
      {
        nome: "Huambo",
        comunas: ["Huambo", "Calima"],
        distritos: [],
        administrador: "Azevedo Manuel Cambiambia",
        data_fundacao: "",
      },
      {
        nome: "Londuimbali",
        comunas: ["Londuimbali", "Ussoque"],
        distritos: [],
        administrador: "Marcos Blasco Cachassile",
        data_fundacao: "",
      },
      {
        nome: "Longonjo",
        comunas: ["Longonjo", "Lépi"],
        distritos: [],
        administrador: "Wilni Fernada Inácio Ekuikui",
        data_fundacao: "",
      },
      {
        nome: "Mungo",
        comunas: ["Mungo", "Cambuengo"],
        distritos: [],
        administrador: "João Kalupeteka Chieva",
        data_fundacao: "",
      },
      {
        nome: "Ucuma",
        comunas: ["Ucuma", "Cacoma", "Mundundo"],
        distritos: [],
        administrador: "Justino Jupter Kandjeke",
        data_fundacao: "",
      },
      {
        nome: "Bimbe",
        comunas: ["Bimbe", "Hengue"],
        distritos: [],
        administrador: "Tomás Sancho Sumbelelo",
        data_fundacao: "",
      },
      {
        nome: "Sambo",
        comunas: ["Sambo", "Samboto"],
        distritos: [],
        administrador: "Aristides Chicuambi Ukuessunga",
        data_fundacao: "",
      },
      {
        nome: "Galanga",
        comunas: ["Galanga", "Cumbira"],
        distritos: [],
        administrador: "Carlota Chilonga",
        data_fundacao: "",
      },
      {
        nome: "Alto Hama",
        comunas: [],
        distritos: [],
        administrador: "Júlio Chimbilundo de Paiva",
        data_fundacao: "",
      },
      {
        nome: "Chilata",
        comunas: [],
        distritos: [],
        administrador: "Feliciana Jinga Lumbwabwa",
        data_fundacao: "",
      },
      {
        nome: "Cuima",
        comunas: ["Cuima", "Catata"],
        distritos: [],
        administrador: "Maria Luisa Liambango",
        data_fundacao: "",
      },
    ],
    informacoes_adicionais: {
      capital: "Huambo",
      linguas: ["Português", "Umbundu"],
      densidade_populacional: "0",
      data_fundacao: "1912-08-08",
      extensao: "2609 km²",
      etnia: ["Ovimbundu"],
      numero_municipios: 17,
    },
  },
  {
    provincia: "Bié",
    governador: {
      nome: "Celeste Elavoco David Adolfo",
      data_nomeacao: "2024-07-15",
    },
    vice_governadores: [
      {
        cargo: "Vice-Governadora para o Sector Político, Social e Econômico",
        nome: "Alcida Celeste de Jesus Camateli",
      },
      {
        cargo: "Vice-Governador para os Serviços Técnicos e Infra-Estruturas",
        nome: "José Fernando Tchatuvela",
      },
    ],
    municipios: [
      {
        nome: "Andulo",
        comunas: ["Andulo", "Cassumbe", "Chivaúlo"],
        distritos: [],
        administrador: "Justino Kassoma Covi",
        data_fundacao: "",
      },
      {
        nome: "Camacupa",
        comunas: ["Camacupa", "Cuanza", "Muinha"],
        distritos: [],
        administrador: "Deolinda Belvina Gonçalves",
        data_fundacao: "",
      },
      {
        nome: "Catabola",
        comunas: ["Catabola", "Caiuera", "Sande"],
        distritos: [],
        administrador: "Madalena Vihemba Segunda Wanga da Silva",
        data_fundacao: "",
      },
      {
        nome: "Chinguar",
        comunas: ["Chinguar", "Cutato", "Cangote"],
        distritos: [],
        administrador: "Ângela Dolina Albino Chicomo Ucueianga",
        data_fundacao: "",
      },
      {
        nome: "Chitembo",
        comunas: ["Chitembo", "Cachingues", "Malengue"],
        distritos: [],
        administrador: "Alexandre José Celestino",
        data_fundacao: "",
      },
      {
        nome: "Cuemba",
        comunas: ["Cuemba", "Munhango", "Sachinemuna"],
        distritos: [],
        administrador: "Baptista Canõlossi Jambela Albino",
        data_fundacao: "",
      },
      {
        nome: "Cuito",
        comunas: ["Cuito", "Cunje"],
        distritos: [],
        administrador: "Abel Guerra Paulo",
        data_fundacao: "",
      },
      {
        nome: "Cunhinga",
        comunas: [],
        distritos: [],
        administrador: "Jorgina Isabel Tchiocana Lumati",
        data_fundacao: "",
      },
      {
        nome: "Nharêa",
        comunas: ["Nharêa", "Gamba", "Caieie"],
        distritos: [],
        administrador: "Neves Bambi Jamba Chissonde",
        data_fundacao: "1965-08-15",
      },
    ],
    informacoes_adicionais: {
      capital: "Cuito",
      linguas: ["Português", "Umbundo"],
      densidade_populacional: "0",
      data_fundacao: "1922-01-05",
      extensao: "70.314 km²",
      etnia: ["Bailundo"],
      numero_municipios: 19,
    },
  },
  {
    provincia: "Cuanza-Sul",
    governador: {
      nome: "Narciso Damásio dos Santos Benedito",
      data_nomeacao: "2024-12-17",
    },
    vice_governadores: [
      {
        cargo: "Vice-Governadora para o Sector Político, Social e Econômico",
        nome: "Emília Cambundo Tchinawalile António Salles Camuhoto",
      },
      {
        cargo: "Vice-Governador para os Serviços Técnicos e Infra-Estruturas",
        nome: "Heitor Dário de José Henriques Alfredo",
      },
    ],
    municipios: [
      {
        nome: "Gabela",
        comunas: ["Gabela", "Assango"],
        distritos: [],
        administrador: "",
        data_fundacao: "1907-09-28",
      },
      {
        nome: "Cassongue",
        comunas: ["Cassongue", "Atóme", "Dumbi"],
        distritos: [],
        administrador: "Inácio Buta Tito",
        data_fundacao: "",
      },
      {
        nome: "Waku Kungo",
        comunas: [],
        distritos: [],
        administrador: "Francisco Manuel Mateus",
        data_fundacao: "",
      },
      {
        nome: "Conda",
        comunas: ["Cunjo", "Conda"],
        distritos: [],
        administrador: "Adão Da Silva Pereira",
        data_fundacao: "",
      },
      {
        nome: "Ebo",
        comunas: ["Ebo", "Cassanje"],
        distritos: [],
        administrador: "António Kituchi Morais de Oliveira",
        data_fundacao: "",
      },
      {
        nome: "Calulo",
        comunas: ["Calulo", "Cabuta"],
        distritos: [],
        administrador: "Ismael Mulemba",
        data_fundacao: "",
      },
      {
        nome: "Mussende",
        comunas: ["Mussende", "Quipaxi"],
        distritos: [],
        administrador: "Agostinho Miquinho Domingos Casseça",
        data_fundacao: "",
      },
      {
        nome: "Porto Amboim",
        comunas: ["Porto Amboim", "Capolo"],
        distritos: [],
        administrador: "Adérito Jorge António Capiango",
        data_fundacao: "",
      },
      {
        nome: "Quibala",
        comunas: ["Quibala", "Dala Cachibo"],
        distritos: [],
        administrador: "Darcy Afonso Fernandes da Costa",
        data_fundacao: "",
      },
    ],
    informacoes_adicionais: {
      capital: "Sumbe",
      linguas: ["Português", "Kimbundu", "Ubundu"],
      densidade_populacional: "0",
      data_fundacao: "1914-09-15",
      extensao: "55.660 km²",
      etnia: ["Ambundu", "Ovimbundu"],
      numero_municipios: 24,
    },
  },
];
